# Generated by Django 3.2.24 on 2024-02-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../default_profile_nikssd.jpg', upload_to='images/'),
        ),
    ]
